"""user tokens

Revision ID: 028e2c2211c1
Revises: 9b060f46a12b
Create Date: 2022-03-30 18:40:08.130388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028e2c2211c1'
down_revision = '9b060f46a12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
